### ISSUE TITLE
[facebook/remove_comments] Comments fall behind next feed item after expansion

### ISSUE THREAD

**Issue by mbernst** [habitlab/habitlab#111]
<img width="519" alt="screen shot 2016-11-24 at 3 05 59 pm" src="https://cloud.githubusercontent.com/assets/249285/20611008/9a9a4e94-b257-11e6-89c3-1869346e8fec.png">

**Comment by mbernst** [comment]
(The "Grace Woo" item is actually the next feed item.)

Also, the "Show Comments" button doesn't disappear after I show comments.

**Comment by gkovacs** [comment]
fixed
