### ISSUE TITLE
[User Feedback] 1) add to the intervention options page the submit feedback button. …

### ISSUE THREAD

**Issue by habitlab-feedback** [habitlab/habitlab#157]
A user submitted the following via HabitLab's built-in Feedback form:

1) add to the intervention options page the submit feedback button.

implementation notes: because we want to take a screenshot of the page without the intervention info popup showing, this will mean we will have to take the screenshot whenever the user clicks the habitlab options page (in case they click the Submit Feedback button)

2) we should send off info like browser version, habitlab version, perhaps ip address and timezone (to prevent abuse?) when they use the submit feedback button

{}

<img src="http://res.cloudinary.com/dvurypg1a/image/upload/v1486373493/c3ymwmnka4rqh9u2yw3l.jpg"></img>

**Comment by gkovacs** [comment]
in terms of extra info to send, we will also want:

* the URL of the page currently being viewed
* any interventions running on it
* if there's a custom intervention active, perhaps include the complete code of it (and any custom components it is using) - in case users developing custom interventions are reporting bugs
