### ISSUE TITLE
Badges experience could use some polish

### ISSUE THREAD

**Issue by habitlab-feedback** [habitlab/habitlab#162]
A user submitted the following via HabitLab's built-in Feedback form:

Badges experience could use some polish

relevant components:

* all-badges-earned-display http://habitlab.github.io/to?tag=all-badges-earned-display

* badges-earned-display http://habitlab.github.io/to?tag=all-badges-earned-display

* badge-earned-timesaved http://habitlab.github.io/to?tag=all-badges-earned-display

when you have no badges, all-badges-earned-display is empty (see screenshot)

<img src="http://res.cloudinary.com/dvurypg1a/image/upload/v1486429396/s1pn0raxjhayhtmc7wod.jpg"></img>

I think the badge mockups at https://github.com/habitlab/habitlab/wiki/Designs#badges look more polished than the ones I implemented

{}

**Comment by gkovacs** [comment]
to access the badge display:

https://habitlab.github.io/to?tag=badge-earned-timesaved&minutes_saved=10

**Comment by gkovacs** [comment]
and the intervals at which badges are displayed is at: https://github.com/habitlab/habitlab/blob/master/src/libs_common/badges_utils.ls

**Comment by gkovacs** [comment]
See https://github.com/habitlab/habitlab/wiki/Designs#badges for catherine's mockups
