### ISSUE TITLE
allow users to vote on and leave feedback on interventions after they are seen

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab#334]
this is being implemented as the reward-display-toast-voting component (currently in the carmelle branch)

to preview the component: https://habitlab.github.io/to?q=reward-display-toast-voting component

relevant files: src/components/reward-display-toast-voting component.(js/html)

the relevant properties are listed under the properties section of the js file (ie, intervention_info, goal_info, seconds_saved, seconds_spent, baseline_seconds_spent)

the methods for upvoting interventions are

```
const {
  upvote_intervention,
  downvote_intervention,
  add_feedback_for_intervention,
  get_num_upvotes_for_intervention,
  get_num_downvotes_for_intervention,
  get_feedback_for_intervention,
} = require('libs_common/intervention_feedback_utils')
```

and their usage is illustrated in the methods submit_feedback, thumbs_up_clicked, and thumbs_down_clicked. should you need to look at the source code for those methods it's at libs_backend/intervention_feedback_utils

to get and build:

```
git checkout carmelle
git pull origin carmelle
yarn
gulp clean
gulp
```

**Comment by gkovacs** [comment]
based on feedback at today's flash meeting, another option would be to show the feedback interface after they click the Turn Off button (ie, if the user clicks the "close tab" button or whatever the intervention wants them to do, it's considered "positive feedback", but if the user clicks "Turn Off" we can show a toast asking for what they didn't like about that intervention)

**Comment by cmillar11** [comment]
[chrome-extension://focklaoblihikihlbbkncncplfklpblo/index.html?tag=habitlab-options-popup-v2](url)

**To-do**: Create toast for both dislike button (post-intervention use) and Turn Off button popup (during intervention use; see above link)

Toast Screens: 

- [ ] Part I: Do you want to turn this off permanently? (Buttons Yes/ No)

- [ ] Part II: What did you dislike? (Buttons "Too aggressive," "Feels ineffective," "Broken," maybe "Other"?)

**Comment by gkovacs** [comment]
hypothesis: we can help reduce attrition by giving users a sense of having "choice" and taking into account their feedback, even if the system is doing the selection of interventions

one source of feedback during onboarding:

how intense do you want your interventions to be? (can be changed later in the settings page)

two sources of feedback during regular usage:

post-intervention surveys: shown immediately after the user sees the intervention

surveys when user turns off the intervention

the way this influences intervention selection:

condition 0: no choice. we don't have any mechanism for the end user to provide feedback

condition 1: placebo. we do nothing with the information, but hope that the illusion of choice helps boost retention rates

condition 2: intelligent selection. we cluster interventions according to annoyingness and our algorithm favors giving the more intense interventions to those who had opted into more intense interventions. can adjust over time based on how much the users are turning off interventions.

**Comment by cmillar11** [comment]
complete
