### ISSUE TITLE
Nudges don't work in Vivaldi browser

### ISSUE THREAD

**Issue by travisterrell** [habitlab/habitlab#394]
Vivaldi browser lets you install Habitlab via the Chrome store, and it seems to function normally. Clicking the "Try now" buttons for the nudges load the website and properly demonstrate the nudge. 

However, when visiting nudge-enabled websites during the course of normal browsing, the nudges are not enabled. Can we get this issue fixed?

**Comment by gkovacs** [comment]
I just tested this on the current version of vivaldi with the current release of habitlab, and the nudges work correctly during normal browsing. Closing this issue, please reopen if you are still having the issue
