### ISSUE TITLE
Where is the license?

### ISSUE THREAD

**Issue by tomlukeywood** [habitlab/habitlab#401]
I am unable to find a license with the habit lab source code.
How is habit lab licensed?

if habit lab has no license i suggest using the GNU GPL, this would maximize the good habit lab could do
by ensuring the community always has the ability to improve upon and share it.

(https://www.gnu.org/licenses/licenses.html#GPL)

**Comment by gkovacs** [comment]
yes it is GPL as you can see in package.json https://github.com/habitlab/habitlab/blob/master/package.json I'll add the license file to the repo
