### ISSUE TITLE
habitlab-logo-v2 icon SVG results in 404 in custom intervention

### ISSUE THREAD

**Issue by pamelafox** [habitlab/habitlab#408]
I wrote a Medium Feed Eater based on the Twitter Feed Eater nudge, and it works well except that the habit lab logo is 404ing. The code is here:
https://gist.github.com/pamelafox/85889bf65d56e93e7d26688db4cb2f83
This is what the URL for the image looks like when it loads in the browser: 
`
<img class="intervention-icon" src="chrome-extension://obghclocpdgcekcognpkblghkedcpdgd/interventions/custom/icon.svg">`

Do you know why it 404s? 

Thank you, and thanks for this lovely customizable extension!

**Comment by gkovacs** [comment]
it's 404-ing because I forgot to commit that icon :) will be fixed in the version I will be pushing tonight

**Comment by gkovacs** [comment]
OK this is fixed in the current version (1.0.203)! Also thanks for contributing your intervention, if it's ok with you we may make it available either as a built-in one or in our contributed interventions section (feature coming soon-ish)

**Comment by pamelafox** [comment]
Sure, I'm happy to contribute it in whatever form. I'm working on another one for Twitter, but it's a bit more sophisticated, so it's not ready for primetime yet. Here's my tweet about it: https://twitter.com/pamelafox/status/971853117804355584
