### ISSUE TITLE
youtube prompt before watch simple fixes

### ISSUE THREAD

**Issue by gkovacs** [habitlab/habitlab#412]
1) if you visit a youtube video that has an advertisement the wrong preview duration is shown (shows the duration of the advertisement instead of the duration of the video itself) - just scrape the page for the actual duration

2) for some videos the play button ends up overlaying on top of the message (css z-index increase it)

relevant code is interventions/youtube/prompt_before_watch/frontend.js

**Comment by frankaging** [comment]
Regarding the first issue, I think, the duration of the actual video will only be loaded to the page if the ads are ended. If this is the case, two options might be considered:
    - while ads are playing, we do nothing. When the actual video is started, we pause and alarm.
    - before ads are played, we show the total time spent message instead of the duration. When ads 
       end, we can then display the duration message

**Comment by gkovacs** [comment]
if you unzip and look at the attached file this is what the youtube html looks like when https://www.youtube.com/watch?v=0KSOMA3QBU0 is played and a 15 second advertisement is about to play. you can generate this yourself by opening the developer console, right click the topmost (html) tag and click edit as html, and copy paste it into a text editor. the actual video duration is 3:45 if you search for that string in the file then you'll find it at 5 different locations. I'm not sure which one is stable but it should be possible to extract it via jquery or so

[youtube.html.zip](https://github.com/habitlab/habitlab/files/1831432/youtube.html.zip)

**Comment by gkovacs** [comment]
here's a better example actually. this one is from https://www.youtube.com/watch?v=XjwZAa2EjKA search for 3:57

[youtube.html.zip](https://github.com/habitlab/habitlab/files/1831464/youtube.html.zip)

**Comment by gkovacs** [comment]
they all occur in a big chunk of JSON inside a script tag so JSON.parse is probably what to use. if you can't find the duration for the video (which might happen if youtube changes their own code) falling back on showing the message after the advertisement finishes would also be reasonable

**Comment by gkovacs** [comment]
probably loop over the script tags, and see if they contain window["ytInitialData"] and if it does then parse the next remainder of that line as JSON would be how to do it

**Comment by frankaging** [comment]
I tried to search the string. I think those matches come from those videos (under thumbnails tag) that are on the recommended list. Could you double confirm?

**Comment by gkovacs** [comment]
{"url":"https://i.ytimg.com/vi/XjwZAa2EjKA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==\u0026rs=AOn4CLAB7e2-iXPiHF01MnIWm4R-Wp6niA","width":336,"height":188}]},"title":{"accessibility":{"accessibilityData":{"label":"Katy Perry - Unconditionally (Official) 来自KatyPerryVEVO 4年前 3分钟 57 秒 468,194,725次观看"}},"simpleText":"Katy Perry - Unconditionally (Official)"},"longBylineText":{"runs":[{"text":"KatyPerryVEVO","navigationEndpoint":{"clickTrackingParams":"CHAQpDAYAiITCNzBsNP5-9kCFWkUfgodCzcE9Cj4HTIGcmVsbWZ1","commandMetadata":{"webCommandMetadata":{"url":"/user/KatyPerryVEVO","webPageType":"WEB_PAGE_TYPE_BROWSE"}},"browseEndpoint":{"browseId":"UC-8Q-hLdECwQmaWNwXitYDw","canonicalBaseUrl":"/user/KatyPerryVEVO"}}}]},"viewCountText":{"simpleText":"468,194,725次观看"},"lengthText":{"accessibility":{"accessibilityData":{"label":"3分钟 57 秒"}},"simpleText":"3:57"}

**Comment by gkovacs** [comment]
```
{"url":"https://i.ytimg.com/vi/XjwZAa2EjKA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==\u0026rs=AOn4CLAB7e2-iXPiHF01MnIWm4R-Wp6niA","width":336,"height":188}]},"title":{"accessibility":{"accessibilityData":{"label":"Katy Perry - Unconditionally (Official) 来自KatyPerryVEVO 4年前 3分钟 57 秒 468,194,725次观看"}},"simpleText":"Katy Perry - Unconditionally (Official)"},"longBylineText":{"runs":[{"text":"KatyPerryVEVO","navigationEndpoint":{"clickTrackingParams":"CHAQpDAYAiITCNzBsNP5-9kCFWkUfgodCzcE9Cj4HTIGcmVsbWZ1","commandMetadata":{"webCommandMetadata":{"url":"/user/KatyPerryVEVO","webPageType":"WEB_PAGE_TYPE_BROWSE"}},"browseEndpoint":{"browseId":"UC-8Q-hLdECwQmaWNwXitYDw","canonicalBaseUrl":"/user/KatyPerryVEVO"}}}]},"viewCountText":{"simpleText":"468,194,725次观看"},"lengthText":{"accessibility":{"accessibilityData":{"label":"3分钟 57 秒"}},"simpleText":"3:57"}
```

**Comment by gkovacs** [comment]
^ that one is not from the thumbnail I believe

**Comment by gkovacs** [comment]
if too complicated though just do the simple workaround though

**Comment by gkovacs** [comment]
here it is in slightly nicer format again this is from ytInitialData in https://www.youtube.com/watch?v=XjwZAa2EjKA before the ad starts playing
[unconditionally_ytInitialData.json.zip](https://github.com/habitlab/habitlab/files/1831541/unconditionally_ytInitialData.json.zip)

**Comment by gkovacs** [comment]
ah wait you're right it seems that one doesn't always reliably appear ok just do the workaround then

**Comment by frankaging** [comment]
no problem.
and it is really hard to simulate two exact test cases.

I will try the workaround. I tried to search the 'video-ads' class and 'videoAdUi' using ```document.getElementsByClassName('videoAdUi')```
And use this as a logic to detect whether ads are presented or not. It is not quite stable though. I add this logic to the main. So the main will look like,
```
main() {
  load()
  if (check_ads()) {
    print('ads!')
  } else {
    print('normal!')
  }
}
```
Issue: I click on a video with ads, it will not print 'ads'. It will print only if I click on the second video. I am not quite sure why there is a step delay. Not quite familiar with the scripting call dependency. Do you know why?

**Comment by gkovacs** [comment]
might be a race condition, the content script executes in parallel with youtube itself. maybe add a setTimeout and execute after 5 seconds and see if it fixes your problem, in that case it was a race condition and you can use some of the utility methods like once_avaliable and once_true to ensure that the code waits until some elements are actually loaded/available

**Comment by gkovacs** [comment]
once_available is from libs_frontend/frontend_libs.js it's not standard javascript

**Comment by frankaging** [comment]
Merge request: https://github.com/habitlab/habitlab/commit/23325a598eb04e727cfcd557143c1a9dfe14c22b, please help review it.

Current workflow: ads will play, the overlay will appear after the ads and before the actual video play.
Current issue: detecting ads is still busy waiting. not optimized.

**Comment by gkovacs** [comment]
works merged thanks!
