### ISSUE TITLE
Many functions in nudges simply do not work.

### ISSUE THREAD

**Issue by powermad80** [habitlab/habitlab#455]
Whether I'm creating my own nudges or running the example functions in the tutorial, things like sweetalert2, listing all enabled goals, and get_streak are undefined/not a function. 

Same error every time when a page is loaded "sweetalert is not a function" or some variant based on which function I'm trying to use.

**Comment by jacobray357** [comment]
I think that the issue is probably that you're using require_package() instead of just require(). The nudge editor was recently changed to follow this behavior and the tutorial is being updated.

**Comment by powermad80** [comment]
Ah I see, the non-functioning tutorial bits were in fact using require_package() and changing that to require() made them work properly. Thanks for that!
